### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by craibuc** [craibuc/PsGeotab#11]
These functions need to be renamed:

Get-DateRange -> Get-GeotabDateRange
Get-Diagnostic -> Get-GeotabDiagnostic
Search-FuelTaxDetail -> Search-GeotabFuelTaxDetail
Search-StatusData -> Search-GeotabStatusData

The files' names were changed, but the functions' names didn't.

**Comment by minusInfinite** [comment]
@craibuc  - my apologies, I thought I already had updated the functions in #9 but I renamed all the filenames and exports without updating the function names and moved on to update the tests. I'll get on that asap.
